import { Incident } from './types';

export const mockIncidents: Incident[] = [
  {
    id: '550e8400-e29b-41d4-a716-446655440001',
    clusterId: 'cluster-001',
    incidentType: 'OomKilled',
    namespace: 'payments',
    podName: 'payment-api-7c9d5d',
    nodeName: 'aks-nodepool1-3821',
    restartCount: 4,
    rawContext: JSON.stringify({
      container: 'api',
      memory_limit: '256Mi',
      memory_used_at_kill: '',
      owner_kind: 'Deployment',
      owner_name: 'payment-api',
    }),
    detectedAt: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    detection: 'OOMKilled — container memory limit reached',
    rootCause: 'Memory limit (256Mi) is too low for current workload. Recent deployment increased batch processing size.',
    proposedFix: 'Increase memory limit from 256Mi to 512Mi in the Deployment manifest.',
    confidenceScore: 0.87,
    workloadName: 'payment-api',
    workloadKind: 'Deployment',
    confidencePenaltyReason: null,
    prUrl: 'https://github.com/podpulse-test/repo/pull/42',
    prStatus: 'opened',
    status: 'pr_opened',
    errorMessage: null,
    createdAt: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
  },
  {
    id: '550e8400-e29b-41d4-a716-446655440002',
    clusterId: 'cluster-001',
    incidentType: 'OomKilled',
    namespace: 'default',
    podName: 'worker-job-abc123',
    nodeName: 'aks-nodepool1-3821',
    restartCount: 2,
    rawContext: JSON.stringify({
      container: 'worker',
      memory_limit: '128Mi',
      owner_kind: 'Job',
      owner_name: 'data-processor',
    }),
    detectedAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    detection: 'OOMKilled — container memory limit reached',
    rootCause: 'Memory limit too low for data processing job.',
    proposedFix: 'Increase memory limit to 256Mi.',
    confidenceScore: 0.45,
    workloadName: 'data-processor',
    workloadKind: 'Job',
    confidencePenaltyReason: 'Multiple candidates (2, -0.20); No resources block in candidate (-0.15)',
    prUrl: null,
    prStatus: 'none',
    status: 'below_threshold',
    errorMessage: null,
    createdAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
  },
  {
    id: '550e8400-e29b-41d4-a716-446655440003',
    clusterId: 'cluster-001',
    incidentType: 'OomKilled',
    namespace: 'staging',
    podName: 'api-server-xyz',
    nodeName: 'aks-nodepool1-3822',
    restartCount: 1,
    rawContext: '{}',
    detectedAt: new Date(Date.now() - 1000 * 60 * 2).toISOString(),
    detection: null,
    rootCause: null,
    proposedFix: null,
    confidenceScore: null,
    workloadName: null,
    workloadKind: null,
    confidencePenaltyReason: null,
    prUrl: null,
    prStatus: 'none',
    status: 'diagnosing',
    errorMessage: null,
    createdAt: new Date(Date.now() - 1000 * 60 * 2).toISOString(),
  },
];